name: Manage GitHub Actions Variables

on:
  workflow_dispatch:
    inputs:
      variable_name:
        description: "Nome da vari치vel"
        required: true
        default: "MY_VARIABLE"
      variable_value:
        description: "Valor da vari치vel"
        required: true

permissions:
  actions: write  # 游댠 Permiss칚o necess치ria para modificar vari치veis do reposit칩rio

jobs:
  manage_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Criar ou Atualizar vari치vel no GitHub Actions
        run: |
          echo "Criando ou atualizando vari치vel no GitHub Actions..."
          gh variable set "${{ github.event.inputs.variable_name }}" --body "${{ github.event.inputs.variable_value }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
