name: Manage GitHub Actions Variables

on:
  workflow_dispatch:

jobs:
  manage_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar se existe a secret ou environment ACTIONS_STEP_DEBUG
        run: |
          if [[ -n "${{ secrets.ACTIONS_STEP_DEBUG }}" || -n "${{ env.ACTIONS_STEP_DEBUG }}" ]]; then
            echo "A variável ACTIONS_STEP_DEBUG está definida."
          else
            echo "A variável ACTIONS_STEP_DEBUG não está definida."
          fi
