name: Manage GitHub Variables

on:
  workflow_dispatch:
    inputs:
      variable_name:
        description: "Nome da vari치vel"
        required: true
        default: "MY_VARIABLE"
      variable_value:
        description: "Valor da vari치vel"
        required: true

permissions:
  actions: write  # 游댠 Necess치rio para gerenciar variables do reposit칩rio

jobs:
  manage_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Criar ou Atualizar uma vari치vel no GitHub Actions
        run: |
          VAR_NAME=${{ github.event.inputs.variable_name }}
          VAR_VALUE=${{ github.event.inputs.variable_value }}
          GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          REPO=${{ github.repository }}

          curl -X PUT -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"name\":\"$VAR_NAME\",\"value\":\"$VAR_VALUE\"}" \
            https://api.github.com/repos/$REPO/actions/variables/$VAR_NAME
